//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Satis_Website.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracKapasite
    {
        public int ARACKAPASITEID { get; set; }
        public Nullable<int> ARACUZUNLUK { get; set; }
        public Nullable<int> ARACGENISLIK { get; set; }
        public Nullable<int> ARACYUKSEKLIK { get; set; }
        public Nullable<int> ARACAGIRLIK { get; set; }
        public Nullable<int> ARACBOSAGIRLIK { get; set; }
        public Nullable<int> ARACKOLTUKSAYISI { get; set; }
        public Nullable<int> ARACBAGAJHACIM { get; set; }
        public Nullable<int> ARACAKSARALIK { get; set; }
        public Nullable<int> ILAN { get; set; }
    
        public virtual Ilan Ilan1 { get; set; }
    }
}
