//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Satis_Website.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracDonanım
    {
        public int DONANIMID { get; set; }
        public string DONANIMIC { get; set; }
        public string DONANIMDIS { get; set; }
        public string DONANIMEGLENCE { get; set; }
        public string DONANIMGUVENLIK { get; set; }
        public Nullable<int> İLAN { get; set; }
    
        public virtual Ilan Ilan { get; set; }
    }
}
