//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Satis_Website.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracGenelBakis
    {
        public int ARACID { get; set; }
        public string ARACYIL { get; set; }
        public string ARACYAKITTIPI { get; set; }
        public string ARACVITESTIPI { get; set; }
        public string ARACKASATIPI { get; set; }
        public string ARACKM { get; set; }
        public string ARACTURU { get; set; }
        public string ARACRENK { get; set; }
        public string ARACPLAKAUYRUK { get; set; }
        public string ARACGARANTIDURUM { get; set; }
        public string ARACILKSAHIP { get; set; }
        public string ARACTAKAS { get; set; }
        public string ARACKIMDEN { get; set; }
        public Nullable<decimal> ARACYILLIKMTV { get; set; }
        public string ARACSANZIMAN { get; set; }
        public Nullable<int> İLAN { get; set; }
    
        public virtual Ilan Ilan { get; set; }
    }
}
