//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Satis_Website.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ilan()
        {
            this.AracDonanım = new HashSet<AracDonanım>();
            this.AracGenelBakis = new HashSet<AracGenelBakis>();
            this.AracKapasite = new HashSet<AracKapasite>();
            this.AracMotorPerformans = new HashSet<AracMotorPerformans>();
            this.AracYakıt = new HashSet<AracYakıt>();
            this.Uye = new HashSet<Uye>();
        }
    
        public int ILANID { get; set; }
        public Nullable<decimal> ILANFIYAT { get; set; }
        public string ILANADRES { get; set; }
        public string ILANNO { get; set; }
        public Nullable<System.DateTime> ILANTARIH { get; set; }
        public string ILANMARKA { get; set; }
        public string ILANSERI { get; set; }
        public string İLANMODEL { get; set; }
        public string ILANARACYIL { get; set; }
        public string ILANYAKITTIPI { get; set; }
        public string ILANVITESTIPI { get; set; }
        public string ILANMOTORHACIM { get; set; }
        public string ILANMOTORGUCU { get; set; }
        public string ILANKM { get; set; }
        public string ILANBOYADEGISEN { get; set; }
        public string ILANTAKASDURUM { get; set; }
        public string ILANKIMDEN { get; set; }
        public string ILANARACGORSEL { get; set; }
        public string ILANBASLIKACIKLAMA { get; set; }
        public Nullable<bool> ILANDURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracDonanım> AracDonanım { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracGenelBakis> AracGenelBakis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracKapasite> AracKapasite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracMotorPerformans> AracMotorPerformans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracYakıt> AracYakıt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uye> Uye { get; set; }
    }
}
