//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Satis_Website.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Oto_SatisEntities : DbContext
    {
        public Oto_SatisEntities()
            : base("name=Oto_SatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AracDonanım> AracDonanım { get; set; }
        public virtual DbSet<AracGenelBakis> AracGenelBakis { get; set; }
        public virtual DbSet<AracKapasite> AracKapasite { get; set; }
        public virtual DbSet<AracMotorPerformans> AracMotorPerformans { get; set; }
        public virtual DbSet<AracYakıt> AracYakıt { get; set; }
        public virtual DbSet<Ilan> Ilan { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
