//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Satis_Website.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public int UYEID { get; set; }
        public string UYEAD { get; set; }
        public string UYESOYAD { get; set; }
        public string UYETELEFON { get; set; }
        public string UYEMAIL { get; set; }
        public string UYESIFRE { get; set; }
        public string UYEADRES { get; set; }
        public Nullable<System.DateTime> UYELIKTARIH { get; set; }
        public Nullable<int> UYEILANHAKKI { get; set; }
        public Nullable<int> ILAN { get; set; }
    
        public virtual Ilan Ilan1 { get; set; }
    }
}
